name: Shelly Scheduler - Gîte

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-scheduler:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Run Shelly Scheduler
        run: python shelly_scheduler.py
